(defun guest_booking ()
  (let ((guest_id nil))
  (format t "~&Please enter guest id: ")
  (setf guest_id (read))
  (list guest_id))
  (format t "Viewed guest bookings with guest ID")
  (menu)
)

(defun room_booking ()
  (let ((room_number nil))
  (format t "~&Please enter room number: ")
  (setf room_number (read))
  (list room_number))
  (format t "Viewed room booking with room number")
  (menu)
)

(defun add_guest ()
  (let ((guest_name nil))
  (format t "~&Please enter guest name: ")
  (setf guest_name (read))
  (list guest_name))
  (format t "A guest has been created with a guest ID")
  (menu)
)
(defun add_room ()
  (let ((room_booking_id nil)
        (room_capacity nil))
  (format t "~&Please enter room number: ")
  (setf room_booking_id (read))
  (format t "~&Please enter room capacity: ")
  (setf room_capacity (read))
  (list room_booking_id room_capacity))
  (format t "A room has been created with a room capacity")
  (menu)
)
(defun add_booking ()
  (let ((guest_id nil)
        (room_booking_id nil)
        (room_capacity nil))
  (format t "~&Please enter guest ID: ")
  (setf guest_id (read))
  (format t "~&Please enter room number: ")
  (setf room_booking_id (read))
  (format t "~&Please enter room capacity: ")
  (setf room_capacity (read))
  (list guest_id room_booking_id room_capacity))
  (format t "*** Booking successful! ***")
  (menu)
)
(defun view_bookings ()
 (format t "~%-----------------------------------------------~%")
 (format t "Sub Menu - Would you like view :~%") 
 (format t "-----------------------------------------------~%")
 (format t "1. Guest bookings~%")
 (format t "2. Room booking~%")
 (format t "Enter choice (1 or 2):~%") 
(setq value (read))
(if (= value 1)
(progn
    (guest_booking)))
(if (= value 2)
(progn
    (room_booking)))

)
(defun quit_booking ()
 (QUIT)
 (menu)
)
(defun menu ()
(format t "~%-----------------------------------------------~%")
(format t "------ Welcome to FedUni Hotel Bookings -------~%")
(format t "-----------------------------------------------~%")
(format t "Main Menu - please select an option:~%")
(format t "1.)     Add guest~%")
(format t "2.)     Add room~%")
(format t "3.)     Add booking~%")
(format t "4.)     View bookings~%")
(format t "5.)     Quit~%")
(format t "Enter choice (1, 2, 3, 4 or 5):~%") 
(setq value (read))
(if (= value 1)
(progn
    (add_guest)))
(if (= value 2)
(progn
    (add_room)))
(if (= value 3)
(progn
    (add_booking)))
(if (= value 4)
(progn
    (view_bookings)))
(if (= value 5)
(progn
    (print "Thanks for using FedUni Hotel Bookings!")
    (quit_booking))
)
)
(menu)
